// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3uA8NKX9NOT2_xFw34eAmp5UFmj2L6Ns',
    appId: '1:958637124532:web:2c52fdefd3f0ba6b6ae0e1',
    messagingSenderId: '958637124532',
    projectId: 'bt-login-flutter',
    authDomain: 'bt-login-flutter.firebaseapp.com',
    storageBucket: 'bt-login-flutter.firebasestorage.app',
    measurementId: 'G-EE496S6M79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi7qVloa01ZUTCetwdHkoug27uP244gHo',
    appId: '1:958637124532:android:b5841f0931c34e936ae0e1',
    messagingSenderId: '958637124532',
    projectId: 'bt-login-flutter',
    storageBucket: 'bt-login-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSixaza6ZitD9Szree1vf5uP3GaLCzUsg',
    appId: '1:958637124532:ios:42789b8dfaa8315e6ae0e1',
    messagingSenderId: '958637124532',
    projectId: 'bt-login-flutter',
    storageBucket: 'bt-login-flutter.firebasestorage.app',
    iosBundleId: 'com.example.btlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSixaza6ZitD9Szree1vf5uP3GaLCzUsg',
    appId: '1:958637124532:ios:42789b8dfaa8315e6ae0e1',
    messagingSenderId: '958637124532',
    projectId: 'bt-login-flutter',
    storageBucket: 'bt-login-flutter.firebasestorage.app',
    iosBundleId: 'com.example.btlogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3uA8NKX9NOT2_xFw34eAmp5UFmj2L6Ns',
    appId: '1:958637124532:web:5a9950d49548d5bd6ae0e1',
    messagingSenderId: '958637124532',
    projectId: 'bt-login-flutter',
    authDomain: 'bt-login-flutter.firebaseapp.com',
    storageBucket: 'bt-login-flutter.firebasestorage.app',
    measurementId: 'G-KVJ5FQ4S48',
  );
}
